"use client";

import { useEffect, useMemo, useReducer, useState, type ReactNode } from "react";

import { deriveSprintOneOneAttention, deriveSprintOneOneCompleteness } from "@/clinical/prototypes/sprint-1-1/derivations";
import { generateSprintOneOneJournal } from "@/clinical/prototypes/sprint-1-1/documents";
import { SPRINT_ONE_ONE_CASE, SPRINT_ONE_ONE_CASE_ACTIONS } from "@/clinical/prototypes/sprint-1-1/fixtures";
import { createEmptySprintOneOneState, type PainProvocation, type PalpationFinding, type SprintOneOneHistory, type SprintOneOneObjective } from "@/clinical/prototypes/sprint-1-1/model";
import { sprintOneOneReducer, type SprintOneOneAction } from "@/clinical/prototypes/sprint-1-1/reducer";

import base from "./SprintOneOnePrototypeBase.module.css";
import styles from "./SprintOneOnePrototype.module.css";

interface Option { readonly value: string; readonly label: string }

function Select({ label, value, options, onChange }: { readonly label: string; readonly value?: string; readonly options: readonly Option[]; readonly onChange: (value: string | undefined) => void }) {
  return <label className={base.field}><span>{label}</span><select value={value ?? ""} onChange={(event) => onChange(event.target.value || undefined)}><option value="">Ikke afklaret</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
}

function TextCommit({ label, value, placeholder, multiline = false, onCommit }: { readonly label: string; readonly value?: string; readonly placeholder?: string; readonly multiline?: boolean; readonly onCommit: (value: string | undefined) => void }) {
  const [draft, setDraft] = useState(value ?? "");
  useEffect(() => setDraft(value ?? ""), [value]);
  const props = { value: draft, placeholder, onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setDraft(event.target.value), onBlur: () => onCommit(draft) };
  return <label className={base.field}><span>{label}</span>{multiline ? <textarea {...props} /> : <input {...props} />}</label>;
}

function NumberCommit({ label, value, onCommit }: { readonly label: string; readonly value?: number; readonly onCommit: (value: number | undefined) => void }) {
  const [draft, setDraft] = useState(value === undefined ? "" : String(value));
  useEffect(() => setDraft(value === undefined ? "" : String(value)), [value]);
  return <label className={base.field}><span>{label}</span><div className={styles.degreeInput}><input aria-label={label} inputMode="decimal" value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={() => { const parsed = Number(draft.replace(",", ".")); onCommit(draft.trim() && Number.isFinite(parsed) ? parsed : undefined); }} /><span>°</span></div></label>;
}

function MultiChoice<T extends string>({ label, values, selected, onToggle }: { readonly label: string; readonly values: readonly { readonly value: T; readonly label: string }[]; readonly selected: readonly T[]; readonly onToggle: (value: T) => void }) {
  return <fieldset className={styles.multi}><legend>{label}</legend><div>{values.map((item) => <button key={item.value} type="button" aria-pressed={selected.includes(item.value)} onClick={() => onToggle(item.value)}>{item.label}</button>)}</div></fieldset>;
}

function Section({ id, number, title, intro, children }: { readonly id: string; readonly number: string; readonly title: string; readonly intro: string; readonly children: ReactNode }) {
  return <section id={id} className={base.section}><header><span>{number}</span><h2>{title}</h2></header><p className={base.narrative}>{intro}</p>{children}</section>;
}

const yesNoUnknown = [{ value: "yes", label: "Ja" }, { value: "no", label: "Nej" }, { value: "not-assessed", label: "Ikke vurderet" }] as const;
const tests = [{ value: "negative", label: "Negativ" }, { value: "positive", label: "Positiv" }, { value: "not-performed", label: "Ikke udført" }, { value: "not-assessable", label: "Ikke vurderbar" }] as const;
const provocations = [{ value: "walking", label: "Gang" }, { value: "stairs", label: "Trapper" }, { value: "rotation", label: "Rotation" }, { value: "running", label: "Løb" }, { value: "jumping", label: "Hop" }, { value: "direction-change", label: "Retningsskift" }] as const;
const palpations = [{ value: "medial-joint-line", label: "Medial ledlinje" }, { value: "lateral-joint-line", label: "Lateral ledlinje" }, { value: "mcl", label: "MCL" }, { value: "lcl", label: "LCL" }, { value: "patella", label: "Patella" }, { value: "patellar-tendon", label: "Patellasene" }, { value: "quadriceps-tendon", label: "Quadricepssene" }, { value: "pes-anserinus", label: "Pes anserinus" }] as const;

export function SprintOneOnePrototype() {
  const [state, dispatch] = useReducer(sprintOneOneReducer, undefined, createEmptySprintOneOneState);
  const [draftOverride, setDraftOverride] = useState<{ source: string; text: string }>();
  const [copyFeedback, setCopyFeedback] = useState("");
  const completeness = useMemo(() => deriveSprintOneOneCompleteness(state), [state]);
  const attention = useMemo(() => deriveSprintOneOneAttention(state), [state]);
  const journal = useMemo(() => generateSprintOneOneJournal(state), [state]);
  const stale = Boolean(draftOverride && draftOverride.source !== journal.text);
  const journalText = draftOverride?.text ?? journal.text;

  function setHistory<K extends Exclude<keyof SprintOneOneHistory, "provocations">>(key: K, value: SprintOneOneHistory[K] | undefined) { dispatch({ type: "set-history", key, value } as SprintOneOneAction); }
  function setObjective<K extends Exclude<keyof SprintOneOneObjective, "palpationFindings">>(key: K, value: SprintOneOneObjective[K] | undefined) { dispatch({ type: "set-objective", key, value } as SprintOneOneAction); }
  function recordSource() { for (const action of SPRINT_ONE_ONE_CASE_ACTIONS) dispatch(action); }
  const nextId = completeness.firstIncomplete === "history" ? "anamnese" : completeness.firstIncomplete === "objective" || completeness.firstIncomplete === "safety" ? "objektivt" : completeness.firstIncomplete === "assessment" ? "vurdering" : "plan";

  async function copyJournal() {
    if (journal.status !== "ready-for-review" || stale || !journalText.trim()) return;
    await navigator.clipboard.writeText(journalText);
    setCopyFeedback("Journaludkast kopieret. Ingen afsendelse er foretaget.");
  }

  return <main className={base.shell}>
    <header className={base.topbar}><div className={base.brand}><span>C</span><div><strong>Cortex</strong><small>Sprint 1.1 · learning prototype</small></div></div><nav aria-label="Konsultationsafsnit"><a href="#anamnese">Anamnese</a><a href="#objektivt">Objektivt</a><a href="#vurdering">Vurdering</a><a href="#plan">Plan</a><a href="#journal">Journal</a></nav></header>
    <div className={base.notice}><strong>Kun syntetiske data.</strong> Dette er en læringsprototype, ikke klinisk validering eller beslutningsstøtte til brug i patientbehandling.</div>
    <div className={base.layout}>
      <aside className={`${base.overview} ${styles.overview}`} aria-label="Cortex Overblik">
        <header><span>Cortex Overblik</span><h1>{SPRINT_ONE_ONE_CASE.title}</h1><p>{SPRINT_ONE_ONE_CASE.demographics} · {SPRINT_ONE_ONE_CASE.id}</p></header>
        <section><h2>Vurderingsgrundlag</h2><ul className={base.completeness}>{completeness.domains.map((domain) => <li key={domain.id}><span aria-hidden="true">{domain.status === "complete" ? "✓" : "○"}</span><div><strong>{domain.label}</strong><small>{domain.summary}</small>{domain.missing.length > 0 && <em>{domain.missing.slice(0, 3).join(" · ")}{domain.missing.length > 3 ? ` +${domain.missing.length - 3}` : ""}</em>}</div></li>)}</ul></section>
        <section className={styles.attention}><h2>Klinisk opmærksomhed</h2>{attention.length ? <ul>{attention.map((item) => <li key={item.id}><strong>{item.question}</strong><span>{item.rationale}</span><small>{item.basis === "missing-information" ? "Grundlag: manglende information" : "Grundlag: klinikerregistreret information"}</small></li>)}</ul> : <p>Ingen yderligere punkter afledt af prototype-state. Det udelukker ikke klinisk risiko.</p>}<p className={styles.authority}>Cortex stiller spørgsmål. Klinikeren vurderer og beslutter.</p></section>
        <p className={base.disclaimer}>{completeness.disclaimer}</p><a className={base.nextAction} href={`#${nextId}`}>Næste: {completeness.domains.find((domain) => domain.id === completeness.firstIncomplete)?.label ?? "gennemgå journal"}</a>
      </aside>

      <div className={base.document}>
        <header className={base.documentHeader}><span>Problem</span><h1>Knæsmerter</h1><p>{SPRINT_ONE_ONE_CASE.source.join(" ")}</p><div className={styles.sourceBoundary}><div><strong>Synlig kilde</strong><ul>{SPRINT_ONE_ONE_CASE.source.map((item) => <li key={item}>{item}</li>)}</ul></div><div><strong>Ikke oplyst</strong><ul>{SPRINT_ONE_ONE_CASE.notProvided.map((item) => <li key={item}>{item}</li>)}</ul></div></div><button type="button" onClick={recordSource}>Brug viste caseoplysninger</button></header>

        <Section id="anamnese" number="01" title="Anamnese" intro={journal.text.split("\n\n").find((part) => part.startsWith("Anamnese"))?.replace("Anamnese\n", "") ?? "Anamnesen opbygges af eksplicit afklarede oplysninger."}>
          <div className={styles.subsection}><h3>Debut og forløb</h3><div className={base.fields}><Select label="Side" value={state.history.side} options={[{value:"right",label:"Højre"},{value:"left",label:"Venstre"}]} onChange={(value) => setHistory("side", value as SprintOneOneHistory["side"])} /><Select label="Debut" value={state.history.onset} options={[{value:"acute",label:"Akut"},{value:"insidious",label:"Snigende"},{value:"gradual",label:"Gradvist indsættende"}]} onChange={(value) => setHistory("onset", value as SprintOneOneHistory["onset"])} /><TextCommit label="Varighed" value={state.history.duration} placeholder="fx siden i går" onCommit={(value) => setHistory("duration", value)} /><Select label="Smerteforløb" value={state.history.painCourse} options={[{value:"constant",label:"Konstant"},{value:"intermittent",label:"Intermitterende"},{value:"increasing",label:"Tiltagende"},{value:"decreasing",label:"Aftagende"}]} onChange={(value) => setHistory("painCourse", value as SprintOneOneHistory["painCourse"])} /></div></div>
          <div className={styles.subsection}><h3>Traume og smerte</h3><div className={base.fields}><Select label="Traume" value={state.history.trauma} options={[{value:"yes",label:"Ja"},{value:"no",label:"Nej"}]} onChange={(value) => setHistory("trauma", value as SprintOneOneHistory["trauma"])} />{state.history.trauma === "yes" && <><Select label="Traumemekanisme" value={state.history.traumaMechanism} options={[{value:"twisting",label:"Vrid"},{value:"direct-blow",label:"Direkte traume"},{value:"fall",label:"Fald"},{value:"other",label:"Andet"}]} onChange={(value) => setHistory("traumaMechanism", value as SprintOneOneHistory["traumaMechanism"])} /><TextCommit label="Traumekontekst" value={state.history.traumaContext} placeholder="fx under fodbold" onCommit={(value) => setHistory("traumaContext", value)} /></>}<Select label="Smerteplacering" value={state.history.painLocation} options={[{value:"medial",label:"Medial"},{value:"lateral",label:"Lateral"},{value:"anterior",label:"Forreste"},{value:"posterior",label:"Bageste"},{value:"diffuse",label:"Diffus"}]} onChange={(value) => setHistory("painLocation", value as SprintOneOneHistory["painLocation"])} /></div><MultiChoice label="Smerteprovokation – flere kan vælges" values={provocations} selected={state.history.provocations} onToggle={(value: PainProvocation) => dispatch({type:"toggle-provocation",value})} /></div>
          <div className={styles.subsection}><h3>Funktion og ledsagesymptomer</h3><div className={base.fields}><Select label="Funktionsevne" value={state.history.function} options={[{value:"unaffected",label:"Upåvirket"},{value:"mildly-reduced",label:"Let nedsat"},{value:"significantly-reduced",label:"Betydeligt nedsat"},{value:"unable-to-bear-weight",label:"Kan ikke støtte"}]} onChange={(value) => setHistory("function", value as SprintOneOneHistory["function"])} /><Select label="Hævelse" value={state.history.swelling} options={[{value:"none",label:"Ingen"},{value:"mild",label:"Let"},{value:"persistent",label:"Vedvarende"},{value:"marked",label:"Udtalt"}]} onChange={(value) => setHistory("swelling", value as SprintOneOneHistory["swelling"])} />{state.history.swelling && state.history.swelling !== "none" && <TextCommit label="Hævelsens tidsforløb" value={state.history.swellingTiming} placeholder="fx opstået gradvist over timer" onCommit={(value) => setHistory("swellingTiming", value)} />}<Select label="Aflåsning" value={state.history.locking} options={yesNoUnknown} onChange={(value) => setHistory("locking", value as SprintOneOneHistory["locking"])} /><Select label="Instabilitet" value={state.history.instability} options={yesNoUnknown} onChange={(value) => setHistory("instability", value as SprintOneOneHistory["instability"])} /><Select label="Hvilesmerter" value={state.history.restPain} options={yesNoUnknown} onChange={(value) => setHistory("restPain", value as SprintOneOneHistory["restPain"])} /><Select label="Nattesmerter" value={state.history.nightPain} options={yesNoUnknown} onChange={(value) => setHistory("nightPain", value as SprintOneOneHistory["nightPain"])} /></div></div>
        </Section>

        <Section id="objektivt" number="02" title="Objektiv vurdering" intro="Målinger og fund står synligt i dokumentet. Ingen normalværdi er forudvalgt.">
          <div className={styles.subsection}><h3>Basisundersøgelse</h3><div className={base.fields}><Select label="Gang" value={state.objective.gait} options={[{value:"normal",label:"Normal"},{value:"limp",label:"Haltende"},{value:"unable",label:"Kan ikke støtte"},{value:"not-assessed",label:"Ikke vurderet"}]} onChange={(value) => setObjective("gait", value as SprintOneOneObjective["gait"])} /><Select label="Inspektion" value={state.objective.inspection} options={[{value:"no-specific-findings",label:"Uden særlige fund"},{value:"swelling",label:"Hævelse"},{value:"redness",label:"Rødme"},{value:"deformity",label:"Deformitet"},{value:"not-assessed",label:"Ikke vurderet"}]} onChange={(value) => setObjective("inspection", value as SprintOneOneObjective["inspection"])} /><Select label="Effusion" value={state.objective.effusion} options={[{value:"none",label:"Ingen"},{value:"mild",label:"Let"},{value:"moderate",label:"Moderat"},{value:"large",label:"Stor"},{value:"not-assessed",label:"Ikke vurderet"}]} onChange={(value) => setObjective("effusion", value as SprintOneOneObjective["effusion"])} /></div><div className={styles.rom}><h4>ROM</h4><NumberCommit label="Ekstension i grader" value={state.objective.extensionDegrees} onCommit={(value) => setObjective("extensionDegrees", value)} /><NumberCommit label="Fleksion i grader" value={state.objective.flexionDegrees} onCommit={(value) => setObjective("flexionDegrees", value)} /><label className={styles.inlineCheck}><input type="checkbox" checked={Boolean(state.objective.rangeNotAssessable)} onChange={(event) => setObjective("rangeNotAssessable", event.target.checked || undefined)} /> Ikke vurderbar</label></div></div>
          <div className={styles.subsection}><h3>Palpation</h3><Select label="Palpationsstatus" value={state.objective.palpationStatus} options={[{value:"no-focal-tenderness",label:"Ingen fokal ømhed"},{value:"not-performed",label:"Ikke udført"},{value:"not-assessable",label:"Ikke vurderbar"}]} onChange={(value) => setObjective("palpationStatus", value as SprintOneOneObjective["palpationStatus"])} /><MultiChoice label="Ømme strukturer – flere kan vælges" values={palpations} selected={state.objective.palpationFindings} onToggle={(value: PalpationFinding) => dispatch({type:"toggle-palpation",value})} /></div>
          <div className={styles.subsection}><h3>Målrettede knætests</h3><div className={base.fields}><Select label="Lachman" value={state.objective.lachman} options={tests} onChange={(value) => setObjective("lachman", value as SprintOneOneObjective["lachman"])} /><Select label="Valgusstres" value={state.objective.valgus} options={[{value:"stable",label:"Stabil"},{value:"lax",label:"Laksitet"},{value:"painful-no-laxity",label:"Smerte uden laksitet"},{value:"not-performed",label:"Ikke udført"},{value:"not-assessable",label:"Ikke vurderbar"}]} onChange={(value) => setObjective("valgus", value as SprintOneOneObjective["valgus"])} /><Select label="Varusstres" value={state.objective.varus} options={[{value:"stable",label:"Stabil"},{value:"lax",label:"Laksitet"},{value:"painful-no-laxity",label:"Smerte uden laksitet"},{value:"not-performed",label:"Ikke udført"},{value:"not-assessable",label:"Ikke vurderbar"}]} onChange={(value) => setObjective("varus", value as SprintOneOneObjective["varus"])} /><Select label="Menisktest" value={state.objective.meniscalTest} options={tests} onChange={(value) => setObjective("meniscalTest", value as SprintOneOneObjective["meniscalTest"])} /><Select label="Patellatest" value={state.objective.patella} options={tests} onChange={(value) => setObjective("patella", value as SprintOneOneObjective["patella"])} /><Select label="Distal neurovaskulær" value={state.objective.neurovascular} options={[{value:"normal",label:"Normal"},{value:"abnormal",label:"Afvigende"},{value:"not-assessed",label:"Ikke vurderet"},{value:"not-assessable",label:"Ikke vurderbar"}]} onChange={(value) => setObjective("neurovascular", value as SprintOneOneObjective["neurovascular"])} /></div></div>
          <div className={styles.subsection}><h3>Røde flag</h3><div className={base.fields}><Select label="Feber" value={state.history.fever} options={yesNoUnknown} onChange={(value) => setHistory("fever", value as SprintOneOneHistory["fever"])} /><Select label="Almen påvirkning" value={state.history.systemicIllness} options={yesNoUnknown} onChange={(value) => setHistory("systemicIllness", value as SprintOneOneHistory["systemicIllness"])} /><Select label="Rødt, varmt og akut hævet knæ" value={state.history.redHotSwollenJoint} options={yesNoUnknown} onChange={(value) => setHistory("redHotSwollenJoint", value as SprintOneOneHistory["redHotSwollenJoint"])} /></div></div>
        </Section>

        <Section id="vurdering" number="03" title="Klinisk vurdering" intro="Klinikerens egen vurdering er adskilt fra Cortex’ spørgsmål og bliver aldrig udfyldt automatisk."><TextCommit label="Klinikerens vurdering og usikkerhed" value={state.assessment} multiline placeholder="Formulér vurdering og relevant usikkerhed…" onCommit={(value) => dispatch({type:"set-assessment",value})} /></Section>

        <Section id="plan" number="04" title="Plan" intro="Plan, opfølgning og safety-net er eksplicit klinikerindhold."><div className={base.textFields}><TextCommit label="Plan" value={state.plan.management} multiline onCommit={(value) => dispatch({type:"set-plan-text",key:"management",value})} /><TextCommit label="Opfølgning" value={state.plan.followUp} onCommit={(value) => dispatch({type:"set-plan-text",key:"followUp",value})} /><TextCommit label="Safety-net" value={state.plan.safetyNet} multiline onCommit={(value) => dispatch({type:"set-plan-text",key:"safetyNet",value})} /></div><div className={styles.imaging}><label className={styles.inlineCheck}><input type="checkbox" checked={Boolean(state.plan.imagingIntent)} onChange={(event) => dispatch({type:"set-imaging-intent",value:event.target.checked})} /> Billeddiagnostik indgår i klinikerens plan</label>{state.plan.imagingIntent && <Select label="Klinikerens valgte modalitet" value={state.plan.imagingModality} options={[{value:"x-ray",label:"Røntgen"},{value:"mri",label:"MR"}]} onChange={(value) => dispatch({type:"set-imaging-modality",value:value as "x-ray"|"mri"|undefined})} />}</div></Section>

        <section id="journal" className={base.outputs}><header><span>05 · Dokumentation</span><h2>Journal som klinisk kommunikation</h2><p>Alle profiler bruger samme kliniske state. Udkastet bliver ikke en klinisk beslutning.</p><div className={base.levels}>{(["short","standard","extended"] as const).map((level) => <label key={level}><input type="radio" name="s11-documentation-level" checked={state.documentationLevel === level} onChange={() => dispatch({type:"set-documentation-level",value:level})} /> {level === "short" ? "Kort" : level === "standard" ? "Standard" : "Udvidet"}</label>)}</div></header><article className={base.outputCard}><header><div><span>{journal.status === "ready-for-review" ? "Klar til klinikerens gennemgang" : "Foreløbigt udkast"}</span><h3>{state.documentationLevel === "short" ? "Kort" : state.documentationLevel === "standard" ? "Standard" : "Udvidet"} journal</h3></div></header>{journal.missing.length > 0 && <div className={base.missing}><strong>Uafklaret før teknisk klarhed</strong><ul>{journal.missing.map((item) => <li key={item}>{item}</li>)}</ul></div>}{stale && <p className={base.stale}>Clinical state er ændret. Din redigerede tekst er bevaret og skal sammenlignes eller gendannes.</p>}<label className={base.draftEditor}><span>Redigerbart journaludkast</span><textarea value={journalText} placeholder="Journaltekst vises, når kliniske oplysninger er afklaret" onChange={(event) => setDraftOverride({source:draftOverride?.source ?? journal.text,text:event.target.value})} /></label><div className={base.outputActions}>{draftOverride && <button type="button" onClick={() => {setDraftOverride(undefined);setCopyFeedback("Genereret tekst gendannet.");}}>Gendan genereret tekst</button>}<button className={base.primary} type="button" disabled={journal.status !== "ready-for-review" || stale || !journalText.trim()} onClick={copyJournal}>Kopiér journaludkast</button></div>{copyFeedback && <p className={base.feedback} role="status">{copyFeedback}</p>}<small>Redigering ændrer ikke de kliniske facts. Kopiering er ikke afsendelse eller klinisk godkendelse.</small></article></section>
      </div>
    </div>
  </main>;
}
